### PR TITLE
Pdev 1311 custom redis

### PR DESCRIPTION
**Pull request by jrhouston**

### CODE REVIEW

**Comment by nabeelamjad** [comment]
Out of curiosity couldn't we have just placed ``redis.conf`` at the same place as [redis.yml](https://github.com/cloudreach-pdev/conductor-configuration/tree/master/kube) and then modified the Kubernetes deployment to read and apply that since apparently you can do something like this:

```bash
$ docker run -v /myredis/conf/redis.conf:/usr/local/etc/redis/redis.conf --name myredis redis redis-server /usr/local/etc/redis/redis.conf
```

source: [redis docker](https://hub.docker.com/_/redis/)

**Comment by jrhouston** [comment]
@nabeelamjad Wouldn't we need to create a volume on kubernetes so that we could mount redis.conf into the pod to do it that way, though?

**Comment by nabeelamjad** [comment]
I think you may be right, a quick look at https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo it seems you can also mount files from a repo.

In any case I guess this is fine then, we'll probably still need to update the ``redis.yml`` to point to the correct repository.  I would also say that this should be public and not private since there's nothing in here that really matters if it is exposed.

**Comment by jrhouston** [comment]
- [x] Oh neat, I didn't know you could mount a volume from a git repository. In that case, I'll just change this repo to host the config and update the existing redis.yml to mount it.

**Comment by jrhouston** [comment]
@nabeelamjad PR adding the gitRepo: https://github.com/cloudreach-pdev/conductor-configuration/pull/11

**Comment by nabeelamjad** [comment]
:+1:

**Pull request merged**
